FileVersion = 1

[Project]
Name = "plutovg-beef"
DefaultNamespace = "plutovg"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\plutovg_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\plutovg.lib"]
